CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE stats (
  id BIGINT NOT NULL,
   app VARCHAR(64),
   uri VARCHAR(255),
   ip VARCHAR(39),
   created TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_stats PRIMARY KEY (id)
);