CREATE TABLE IF NOT EXISTS users
    (
        id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR(254),
        name  VARCHAR(250) UNIQUE
    );

-- Location

CREATE TABLE IF NOT EXISTS location
    (
        id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lat     DOUBLE PRECISION                        NOT NULL,
        lon     DOUBLE PRECISION                        NOT NULL
    );

-- Category

CREATE TABLE IF NOT EXISTS category
    (
        id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(50) UNIQUE
    );

-- Compilation

CREATE TABLE IF NOT EXISTS compilation
    (
        id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pinned BOOLEAN                                 NOT NULL,
        title  VARCHAR(50)
    );

-- Event

CREATE TABLE IF NOT EXISTS event
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(120) NOT NULL,
        annotation VARCHAR(2000) NOT NULL,
        description VARCHAR(7000),
        category_id BIGINT NOT NULL  REFERENCES category (id),
        initiator_id BIGINT NOT NULL REFERENCES users (id),
        location_id BIGINT NOT NULL  REFERENCES location (id),
        paid BOOLEAN NOT NULL,
        created_on TIMESTAMP WITHOUT TIME ZONE,
        published_on TIMESTAMP WITHOUT TIME ZONE,
        event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        participant_limit INTEGER NOT NULL,
        request_moderation BOOLEAN NOT NULL,
        state VARCHAR(50),
        views BIGINT NOT NULL
    );

-- Request to event

CREATE TABLE IF NOT EXISTS event_request
    (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id     BIGINT REFERENCES event (id) ON DELETE CASCADE,
        requester_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
        created      TIMESTAMP WITHOUT TIME ZONE,
        status       VARCHAR(50)
    );

-- Compilation Events

CREATE TABLE IF NOT EXISTS compilation_events
    (
        compilation_id BIGINT REFERENCES compilation (id) ON DELETE CASCADE,
        event_id       BIGINT REFERENCES event (id) ON DELETE CASCADE
    );
